"""Compile the family DTCG-style foundation tokens; no third-party dependencies."""
from pathlib import Path
import argparse
import json

ROOT = Path(__file__).resolve().parent

def compile_tokens():
    source = json.loads((ROOT / 'tokens.json').read_text())
    version = source['$extensions']['org.metachlorian.family']['version']
    lines = [f'/* Family foundations {version}. Generated by design-system/build.py; edit tokens.json. */', ':root {']
    def visit(group, path=()):
        for name, value in group.items():
            if name.startswith('$'):
                continue
            key = (*path, name)
            if '$value' not in value:
                visit(value, key)
                continue
            raw = value['$value']
            if value['$type'] in ('dimension', 'duration'):
                raw = f"{raw['value']:g}{raw['unit']}"
            lines.append(f"  --family-{'-'.join(key)}: {raw};")
    visit(source)
    return '\n'.join([*lines, '}', ''])

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'foundations.css')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    css = compile_tokens()
    if args.check:
        if not args.output.exists() or args.output.read_text() != css:
            raise SystemExit(f'Stale token export: {args.output}. Run the generator.')
        print(f'PASS: {args.output} matches the versioned token source.')
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(css)
        print(f'Generated {args.output}')
